apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: appnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appnode
  template:
    metadata:
      labels:
        app: appnode
    spec:
      containers:
      - name: appnode
        image: sainishivani/appnode:lts
        ports:
        - containerPort: 9999